CREATE DATABASE IF NOT EXISTS pawnshop CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'pawnshop_admin'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON pawnshop.* TO 'pawnshop_admin'@'localhost';
FLUSH PRIVILEGES;

USE pawnshop;

-- USERS Table
CREATE TABLE IF NOT EXISTS USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    EMAIL VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    PASSWORD VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    ROLE ENUM('admin', 'user') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    CONSTRAINT PK_USERS_ID PRIMARY KEY (ID)
);

-- PRODUCTS Table
CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    PRICE DECIMAL(18,2) NOT NULL,
    MAIN_IMAGE VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    DESCRIPTION VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    CONSTRAINT PK_PRODUCTS_ID PRIMARY KEY (ID)
);

-- PRODUCT_IMAGES Table
CREATE TABLE IF NOT EXISTS PRODUCT_IMAGES (
    ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL,
    IMAGE VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    CONSTRAINT PK_PRODUCT_IMAGES_ID PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_IMAGES_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- SAVED_PRODUCTS Table
CREATE TABLE IF NOT EXISTS SAVED_PRODUCTS (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CONSTRAINT PK_SAVED_PRODUCTS_ID PRIMARY KEY (ID),
    CONSTRAINT FK_SAVED_PRODUCTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SAVED_PRODUCTS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- RESERVED_PRODUCTS Table
CREATE TABLE IF NOT EXISTS RESERVED_PRODUCTS (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CONSTRAINT PK_RESERVED_PRODUCTS_ID PRIMARY KEY (ID),
    CONSTRAINT FK_RESERVED_PRODUCTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_RESERVED_PRODUCTS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- NEGOTIATION_OFFERS Table
CREATE TABLE IF NOT EXISTS NEGOTIATION_OFFERS (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRICE DECIMAL(18,2) NOT NULL,
    OFFER_RESULT ENUM('pending', 'denied') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    CONSTRAINT PK_NEGOTIATION_OFFERS_ID PRIMARY KEY (ID),
    CONSTRAINT FK_NEGOTIATION_OFFERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_NEGOTIATION_OFFERS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);